cc_library(
    name = "text",
    srcs = ["text.cc"],
    hdrs = ["text.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//uchen:runtime",
        "@abseil-cpp//absl/log",
    ],
)
