# cc_test(
#     name = "embeddings_test",
#     srcs = ["embeddings.test.cc"],
#     deps = [
#         "//uchen:runtime",
#         "//uchen/input:text",
#         "@abseil-cpp//absl/log",
#         "@abseil-cpp//absl/log:initialize",
#         "@googletest//:gtest_main",
#     ],
# )

# cc_test(
#     name = "tokenizer_test",
#     srcs = ["tokenizer.test.cc"],
#     data = ["data/test.cc"],
#     deps = [
#         "//uchen/input:text",
#         "@abseil-cpp//absl/log",
#         "@abseil-cpp//absl/log:check",
#         "@googletest//:gtest_main",
#     ],
# )

# cc_test(
#     name = "text_e2e_test",
#     srcs = ["text_e2e.test.cc"],
#     deps = [
#         "//test:test_lib",
#         "//uchen/input:text",
#         "@abseil-cpp//absl/log",
#         "@abseil-cpp//absl/log:check",
#         "@abseil-cpp//absl/log:initialize",
#         "@googletest//:gtest_main",
#     ],
# )
