package(default_visibility = ["//visibility:public"])

cc_library(
    name = "rnn_names",
    srcs = ["rnn_names.cc"],
    hdrs = ["rnn_names.h"],
    deps = [
        "//uchen:rnn",
        "//uchen:runtime",
        "//uchen:softmax",
        "@abseil-cpp//absl/log",
    ],
)
